<?php
/**
 * Shippit Pty Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the terms
 * that is available through the world-wide-web at this URL:
 * http://www.shippit.com/terms
 *
 * @category   Shippit
 * @copyright  Copyright (c) 2016 by Shippit Pty Ltd (http://www.shippit.com)
 * @author     Matthew Muscat <matthew@mamis.com.au>
 * @license    http://www.shippit.com/terms
 */
?>
<?php if ($block->getHelper()->isAuthorityToLeaveActive()): ?>
    <div class="admin__page-section-item order-shipping-method">
        <strong>
            <?php echo $block->escapeHtml(__('Authority To Leave')) ?>
        </strong>
        <span>
            <?php echo ($block->getShippitAuthorityToLeave()) ? 'Yes' : 'No' ?>
        </span>
    </div>
<?php endif ?>

<?php if ($block->getHelper()->isDeliveryInstructionsActive()): ?>
    <div class="admin__page-section-item order-shipping-method">
        <strong>
            <?php echo $block->escapeHtml(__('Delivery Instructions')) ?>
        </strong>
        <span>
            <?php if (empty($block->getShippitDeliveryInstructions())): ?>
                N/A
            <?php else: ?>
                <?php echo $block->escapeHtml($block->getShippitDeliveryInstructions()) ?>
            <?php endif ?>
        </span>
    </div>
<?php endif ?>
