php74-composer:
  extends:
    - .composer
    - .composer-magento-auth
  stage: build
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.4

php74-linter:
  extends: .php-lint
  stage: test
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.4
  needs:
    - php74-composer
