php70-composer:
  extends:
    - .composer
    - .composer-magento-auth
  stage: build
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.0
  script:
    - composer install --prefer-dist --optimize-autoloader --no-progress --no-plugins --no-interaction

php70-linter:
  extends: .php-lint
  stage: test
  needs:
    - php70-composer
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.0
