php70-composer:
  extends:
    - .composer
    - .composer-magento-auth
  stage: build
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.0
  before_script:
    - !reference [.composer-magento-auth, before_script]
    # Remove unsupported dev-packages
    - composer remove bitexpert/phpstan-magento --dev --no-interaction --no-update
    - composer remove phpstan/phpstan --dev --no-interaction --no-update

php70-linter:
  extends: .php-lint
  stage: test
  needs:
    - php70-composer
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:7.0
