php81-composer:
  extends:
    - .composer
    - .composer-magento-auth
  stage: build
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:8.1

php81-linter:
  extends: .php-lint
  stage: test
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:8.1
  needs:
    - php81-composer
